로그인, 프로필 화면 [STEP 1] claire.pp, vapor.park
yagom-academy/ios-login-profile pull request #2
Opened 2022-01-04 06:57 UTC by HanEun-ji

# 로그인, 프로필 화면 [STEP 1] claire.pp, vapor.park
@zdodev 
STEP 1 PR입니다.

안녕하세요 claire & vapor 입니다
STEP 1 - 로그인 화면을 만들며 구현했던 것은 다음과 같습니다.
- 스토리보드 이용, 화면 구성
- 버튼 활성화/비활성화
- 시스템 텍스트 크기 대응
- 지역화(en, ko)

저희는 각자 구현 후, 서로의 프로젝트에 대해 설명 후 합치는 방식을 이용했습니다.
또한 저희는 처음에 회의를 할 때 코딩컨벤션을 지키기 위해 swiftLint를 사용하는 것으로 합의했습니다.

## 화면 구성
스토리보드를 이용해서 화면을 구성했습니다.
component간의 관계를 이용해서 화면을 구성할 수 있도록 했는데, 화면 크기가 달라지더라도 동일한 모습의 화면이 나올 수 있는지를 고민했습니다. 수치는 Figma 디자인 가이드를 참조했습니다.

## 버튼 활성화/비활성화
텍스트필드의 변화를 감지해서 5글자 이상일 경우 버튼의 색을 바꾸고 활성화시켰습니다.
텍스트필드의 변화를 감지하는 방법으로는 delegate, target-action등이 있는데
저희는 각자의 프로젝트에서 target-action과 delegate를 이용했습니다.

* target-action
```Swift
@objc
    func emailTextFieldDidChange(_ sender: UITextField?) {
        guard let text = sender?.text, text.count >= 5 else {
            activateButton(false)
            return
        }
        activateButton(true)
    }
```

* UITextFieldDelegate
```Swift
func textFieldDidChangeSelection(_ textField: UITextField) {
        guard let text = textField.text else {
            loginButton.isSelected = false
            return
        }
        loginButton.isEnabled = text.count >= 5
        loginButton.backgroundColor = text.count >= 5 ? .systemYellow : .systemGray5
    }
```
Delegate는 selector 대신 protocol을 사용하며, 클래스간의 전달이 필요하거나 둘 이상의 기능을 구현해야할 때 유용하다는 것을 알게 되었습니다. 따라서 한 클래스 내에서 텍스트의 글자가 변하는 이벤트를 확인하는 기능은 target-action이 적절하다고 생각해 target-action으로 합쳤습니다.

## 시스템 텍스트 크기 대응
Dynamic type size를 이용해서 적절한 텍스트 크기를 선택했으며,
adjustsFontForContentSizeCategory 프로퍼티를 true로 두어 폰트 크기를 적절하게 리사이즈 할 수 있게 했습니다.

## 지역화
예시처럼 한국어, 영어로 구현을 위해 지역화를 했습니다.
스토리보드 파일을 지역화하여 스토리보드 내에 있는 텍스트들을 영어와 한국어로 지역화하였습니다.

## 궁금한점
* dynamic type을 대응하기 위해 scrollView 사용 
    * 이 브렌치에는 반영하지 않았지만, dynamic type을 적용하여, 폰트가 아주 클 때는 화면이 짤리는 현상을 볼 수 있었습니다.
    * 그래서 UIView대신에 UIScrollView로 안에 뷰들을 배치시켜 구현해보니 폰트가 클수록 스크롤 가능해져 해결했다고 생각합니다.
    * 다만 이 방법이 맞는 방법인지 궁금합니다. 

* 텍스트필드 밑에 separator line 을 UIView로 구현하여 height constraint를 0.5로 줄 경우 실제로 0.5가 되지 않는 문제
    * 이 브렌치에는 1.0으로 되어있는데, 0.5로 줄경우 0.67 같이 소수점이 튀는 현상이 있는데 이유를 잘 모르겠습니다.

## 마무리
처음으로 페어 프로그래밍을 하며 많이 배울 수 있었습니다!
보완이 필요한 사항들에 대한 피드백 주시면 감사하겠습니다!

2022-01-04 13:00 UTC, zdodev requested changes
안녕하세요. @HanEun-ji , @gustn3965 !
두 번째 프로젝트 첫 PR 축하합니다🤩

피그마 디자인 가이드에 따라 잘 적용해주셨습니다!
그리고 각 컴포넌트 오토레이아웃도 기기에 따라 동적으로 변하도록 잘 적용해주셨습니다.👍
지역화 부분도 잘 작성해주셨습니다~

다만 피그마 디자인 가이드와 다르게 설정된 부분이 조금 있습니다.
피그마 코멘트를 확인해보고 적용해보면 좋을 것 같습니다.😁

![1](https://user-images.githubusercontent.com/67548251/148062524-37f14592-0539-4754-ba4c-92e94083ef2b.png)
<img width="712" alt="2" src="https://user-images.githubusercontent.com/67548251/148062559-5e836172-8eda-4f0d-8827-e14354bd294e.png">

---

- dynamic type을 대응하기 위해 scrollView 사용
동적으로 변하는 뷰를 위해서 `scrollView` 를 사용하는 것은 좋은 방법이라고 생각합니다!

- 텍스트필드 밑에 separator line 을 UIView로 구현하여 height constraint를 0.5로 줄 경우 실제로 0.5가 되지 않는 문제
다운로드받은 프로젝트에서 0.5 설정을 해보면 constraint 및 height 가 0.5로 정상적으로 반영됩니다. 사용 환경과 Xcode에 따른 문제이지 않을까 싶습니다. 팀원과 같이 다시 설정해보면 좋을 것 같습니다.

약간의 의견을 남겨보았습니다.
궁금하신 점이 있다면 같이 의견을 나눠보면 좋겠습니다.🤗

2022-01-04 13:00 UTC, zdodev commented on LoginProfile/LoginViewController.swift
> +        super.viewDidLoad()
`target action`을 사용해보셨네요. 좋습니다.👍

2022-01-04 13:00 UTC, zdodev commented on LoginProfile/LoginViewController.swift
> +        // Do any additional setup after loading the view.
불필요한 주석은 제거보는 것이 어떨까요?🤔

2022-01-04 13:00 UTC, zdodev commented on LoginProfile/LoginViewController.swift
> +    func activateButton(_ bool: Bool) {
파라미터명을 단순히 타입명으로 작성하지 않았을까 싶었습니다.
값을 의미하는 이름으로 바꿔보는 것은 어떨까요?🤔
지금 이름으로 진행하셔도 무방합니다!

2022-01-05 04:28 UTC, HanEun-ji commented
안녕하세요! 피드백 주신 내용들 잘 확인했습니다!
피드백에 따라
- parameter명 수정
- 주석 제거
- UI figma 가이드에 맞게 수정
하여 다시 push했습니다!
한번 확인해주시면 감사하겠습니다!!

2022-01-05 05:49 UTC, zdodev approved these changes
안녕하세요. @HanEun-ji , @gustn3965 !

figma 디자인 가이드대로 수정한 사항 확인했습니다~
코드를 많이 작성한것은 아니지만 UI를 구현하시면서 많은 경험을 해보셨을꺼라 생각합니다.😁

다만 로그인 버튼을 활성화하고(`text.count >= 5`을 만족) 버튼을 터치해보셨을까요?
앱이 강제 종료되는 현상이 발생하고 있습니다.😱  이 부분은 팀원분과 의논하면서 다음 스텝에 반영해보면 좋을 것 같습니다.

이번 스텝은 여기서 마무리지어도 될 것 같습니다. 스텝1 진행하시느라 고생하셨습니다~🥳

2022-01-05 05:49 UTC, zdodev commented on LoginProfile/LoginViewController.swift
> +    func activateButton(_ isActive: Bool) {
좋습니다.👍

2022-01-05 05:49 UTC, merged